app_goal:
    type: rest
    resource: "@AppBundle/Resources/config/routing/goal.yml"
    prefix:   /goal

app_tag:
    type: rest
    resource: "@AppBundle/Resources/config/routing/tag.yml"
    prefix:   /tag
