tag_index:
    path:     /
    defaults: { _controller: "AppBundle:Tag:index" }
    methods:  GET

tag_show:
    path:     /{id}/
    defaults: { _controller: "AppBundle:Tag:show" }
    methods:  GET

tag_new:
    path:     /
    defaults: { _controller: "AppBundle:Tag:new" }
    methods:  [POST]

tag_edit:
    path:     /{id}/
    defaults: { _controller: "AppBundle:Tag:edit" }
    methods:  [PUT, PATCH]

tag_delete:
    path:     /{id}/
    defaults: { _controller: "AppBundle:Tag:delete" }
    methods:  DELETE
